# Generated by Django 3.0.4 on 2020-03-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_auto_20200329_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10000)),
                ('transliteration', models.CharField(max_length=100)),
            ],
        ),
    ]
